keys:
  - &cloud a97647f4d6528177a3820b84d1333553d63d36a4
  - &albatross 512a533fdb1899f86137775ad6370e0d4cfeb3b5
  - &bluejay 3eb1bbbf97b5decbda204191aa47717d882fb914
  - &weebill 76e0e477d660fc9a2d3c51be85a9500e177b53d3
  - &yubikey ed835ed426ccbad217134bf2898ea27607d72cce
creation_rules:
  - path_regex: secrets/albatross-builder.yaml
    key_groups:
      - pgp:
          - *yubikey
          - *bluejay
          - *weebill
  - path_regex: secrets/github-gh-token.yaml
    key_groups:
      - pgp:
          - *yubikey
          - *albatross
          - *bluejay
          - *weebill
  - path_regex: secrets/tailscale.yaml
    key_groups:
      - pgp:
          - *yubikey
          - *albatross
          - *bluejay
          - *weebill
  - path_regex: secrets/ursalabs-zulip.yaml
    key_groups:
      - pgp:
          - *yubikey
          - *albatross
          - *bluejay
          - *weebill
  - path_regex: secrets/apache-jira.yaml
    key_groups:
      - pgp:
          - *yubikey
          - *albatross
          - *bluejay
          - *weebill
