keys:
  - &albatross 512a533fdb1899f86137775ad6370e0d4cfeb3b5
  - &bluejay 3eb1bbbf97b5decbda204191aa47717d882fb914
  - &weebill 76e0e477d660fc9a2d3c51be85a9500e177b53d3
  - &yubikey ed835ed426ccbad217134bf2898ea27607d72cce
  - &falcon 349c63c0381298d3a5dd0c6dbc763099cf9d4f6c
  - &plover e28ac8c0cf7d63ce302140c3298a2e9f11f078bf
creation_rules:
  - path_regex: secrets/albatross-builder.yaml
    key_groups:
      - pgp:
          - *yubikey
          - *weebill
          - *falcon
          - *plover
          - *albatross
  - path_regex: secrets/falcon-builder.yaml
    key_groups:
      - pgp:
          - *yubikey
          - *weebill
          - *albatross
          - *plover
          - *falcon
  - path_regex: secrets/github-gh-token.yaml
    key_groups:
      - pgp:
          - *yubikey
          - *albatross
          - *weebill
          - *falcon
          - *plover
  - path_regex: secrets/tailscale.yaml
    key_groups:
      - pgp:
          - *yubikey
          - *albatross
          - *weebill
          - *falcon
          - *plover
  - path_regex: secrets/ursalabs-zulip.yaml
    key_groups:
      - pgp:
          - *yubikey
          - *albatross
          - *weebill
  - path_regex: secrets/apache-jira.yaml
    key_groups:
      - pgp:
          - *yubikey
          - *albatross
          - *weebill
  - path_regex: secrets/cachix.yaml
    key_groups:
      - pgp:
          - *yubikey
          - *albatross
          - *weebill
          - *falcon
          - *plover
