on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: CI

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-unstable-small
          extra_nix_config: |
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v10
        with:
          name: cpcloud-nix-config
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: nix-community
      - run: nix --print-build-logs --keep-going develop --command pre-commit run --all-files
  build:
    strategy:
      fail-fast: false
      matrix:
        system:
          - albatross
          - bluejay
          - falcon
          - weebill
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-unstable-small
          extra_nix_config: |
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v10
        with:
          name: cpcloud-nix-config
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: nix-community
      - run: nix --print-build-logs --keep-going build --no-link '.#hosts.${{ matrix.system }}'
