on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: CI

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        system:
          - albatross
          - bluejay
          - falcon
          - weebill
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v14
        with:
          extra_nix_config: |
            experimental-features = nix-command
      - uses: cachix/cachix-action@v10
        with:
          name: cpcloud-nix-config
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: nix-community
      - run: nix build --keep-going --no-link -L '.#${{ matrix.system }}'
