on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: CI

concurrency:
  group: ${{ github.repository }}-${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable-small
      - uses: cachix/cachix-action@v10
        with:
          name: cpcloud-nix-config
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: nix-community
      - run: nix --print-build-logs --keep-going develop --command pre-commit run --all-files
  get-hosts:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get-hosts.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable-small
      - name: get the current system
        id: get-system
        run: |
          set -euo pipefail

          system="$(nix eval --raw 'nixpkgs#stdenv.system')"
          echo "::set-output name=system::$system"
      - name: generate host list
        id: get-hosts
        run: |
          set -euo pipefail

          expr='builtins.toJSON (import ./nix/hosts.nix)'
          system=${{ steps.get-system.outputs.system }}
          # get hosts ignoring plover
          hosts="$(nix eval --impure --raw --expr "$expr" | jq -rcM --arg system "$system" '{system: [.[] | select(.system == $system).hostname]}')"
          echo "::set-output name=matrix::$hosts"
  build:
    runs-on: ubuntu-latest
    needs:
      - get-hosts
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.get-hosts.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable-small
      - uses: cachix/cachix-action@v10
        with:
          name: cpcloud-nix-config
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: nix-community
      - run: nix --print-build-logs --keep-going build --no-link '.#hosts.${{ matrix.system }}'
