on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: CI

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        system:
          - albatross
          - bluejay
          - pigeon
          - falcon
          - weebill
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v14
      - uses: cachix/cachix-action@v10
        with:
          name: cpcloud-nix-config
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: nix-community

      - name: build ${{ matrix.system }}
        run: nix build --keep-going --file . ${{ matrix.system }}
