on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Continuous Integration

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        system:
          - albatross
          - bluejay
          - pigeon
          - falcon
          - weebill
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v14

      - name: Setup Cachix
        uses: cachix/cachix-action@v10
        with:
          name: cpcloud-nix-config
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          extraPullNames: nix-community

      - name: Build ${{ matrix.system }}
        run: nix build -L -f . ${{ matrix.system }}
