name: Update Deps
on:
  schedule:
    - cron: "* */6 * * *"
  workflow_dispatch:
jobs:
  niv-update:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dep:
          - repo: home-manager
            owner: nix-community
          - repo: nixos-hardware
            owner: NixOS
          - repo: nixpkgs
            owner: NixOS
          - repo: nixus
            owner: Infinisil
          - repo: sops-nix
            owner: Mic92
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main

      - name: Install Nix
        uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable-small

      - name: Setup Cachix
        uses: cachix/cachix-action@v10
        with:
          name: nix-community

      - name: Get current commit
        id: get_current_commit
        run: echo ::set-output name=sha256::$(nix run nixpkgs.jq -c jq -rcM '.["${{ matrix.dep.repo }}"].rev' < nix/sources.json)
        working-directory: main

      - name: Update ${{ matrix.dep.repo }}
        run: nix run nixpkgs.niv -c niv update ${{ matrix.dep.repo }}
        working-directory: main

      - name: Get new commit
        id: get_new_commit
        run: echo ::set-output name=sha256::$(nix run nixpkgs.jq -c jq -rcM '.["${{ matrix.dep.repo }}"].rev' < nix/sources.json)
        working-directory: main

      - name: Get log lines for upstream changes
        id: compute_log_lines
        if: ${{ steps.get_current_commit.outputs.sha256 != steps.get_new_commit.outputs.sha256 }}
        run: echo ::set-output name=log_lines::$(./repo_commits.sh NixOS/nixpkgs ${{ steps.get_current_commit.outputs.sha256 }} ${{ steps.get_new_commit.outputs.sha256 }})
        working-directory: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a pull request to update ${{ matrix.dep.repo }}
        if: ${{ steps.get_current_commit.outputs.sha256 != steps.get_new_commit.outputs.sha256 }}
        uses: peter-evans/create-pull-request@v3
        with:
          path: main
          commit-message: "feat(niv): update ${{ matrix.dep.repo }}"
          branch: "create-pull-request/update-${{ matrix.dep.repo }}"
          delete-branch: true
          title: "feat(niv): update ${{ matrix.dep.repo }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          body: ${{ steps.compute_log_lines.outputs.log_lines }}
