name: Update Deps
on:
  schedule:
    - cron: "* */6 * * *"
  workflow_dispatch:
jobs:
  niv-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create PRs for niv dependencies
        uses: knl/niv-updater-action@v9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          niv_version: "v0.2.19"
          title_prefix: "feat:"
