name: Update Flakes
on:
  schedule:
    - cron: "30 */6 * * *"
  workflow_dispatch:
jobs:
  flake-update:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        input:
          - deploy-rs
          - flake-utils
          - home-manager
          - nixos-hardware
          - nixpkgs
          - pre-commit-hooks
          - sops-nix
          - templates
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable-small
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Setup Cachix
        uses: cachix/cachix-action@v10
        with:
          name: cpcloud-nix-config
          extraPullNames: nix-community

      - uses: tibdex/github-app-token@v1
        id: generate_token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Update ${{ matrix.input }}
        uses: cpcloud/flake-update-action@v1.0.1
        with:
          dependency: ${{ matrix.input }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-token: ${{ steps.generate_token.outputs.token }}
          pull-request-author: "Phillip Ground <cpcloudbot@gmail.com>"
          pull-request-labels: dependencies,autorebase:opt-in
          automerge: true
          delete-branch: true
